using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GoalController : MonoBehaviour
{
    // Start is called before the first frame update
    public Collider2D ball;
    public bool isRight;
    public ScoreManager manager;

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision == ball)
        {
            if (isRight)
            {
                manager.AddRightScore(1);
                SoundManager.Instance._effectSource4.GetComponent<AudioSource>().Play();
            }
            else
            {
                manager.AddLeftScore(1);
                SoundManager.Instance._effectSource4.GetComponent<AudioSource>().Play();
            }
        }
    }
}
